sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2.6

addons:
  postgres: '9.4'

services:
  - postgresql
  - docker

env:
  global:
    - GCP_PROJECT_ID=mypersonal-303304
    - IMAGE=gcr.io/mypersonal-303304/my_personal
    - CLOUD_RUN_SERVICE=mypersonal-303304
    - CLOUD_RUN_REGION=us-central1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)


