sudo: required
language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2.6

addons:
  postgres: '9.4'

services:
  - postgresql
  - docker

env:
  global:
    - GCP_PROJECT_ID=mypersonal-303304
    - IMAGE=gcr.io/mypersonal-303304/my_personal
    - CLOUD_RUN_SERVICE=mypersonal-303304
    - CLOUD_RUN_REGION=us-central1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)
before_install:
  - SUA_CHAVE_CRIPTOGRAFADA
  - curl https://sdk.cloud.google.com | bash > /dev/null #Download SDK GOOGLE
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=SUA_CHAVE_CRIPTOGRAFADA
  - gcloud auth configure-docker # habilita push para o gcr
  - gcloud config set project "${GCP_PROJECT_ID}"
  - gcloud components install beta # until Cloud Run is generally available (GA)
script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh #
  on:
    branch: master
